# Generated by Django 5.2.2 on 2025-06-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('current_stage', models.CharField(choices=[('Submitted', 'Submitted'), ('Under Review', 'Under Review'), ('Interview Stage', 'Interview Stage'), ('Technical Assessment', 'Technical Assessment'), ('Final Interview', 'Final Interview'), ('Offer Extended', 'Offer Extended'), ('Hired', 'Hired'), ('Rejected', 'Rejected')], default='Submitted', max_length=50)),
                ('source', models.CharField(choices=[('LinkedIn', 'LinkedIn'), ('Indeed', 'Indeed'), ('Referral', 'Referral'), ('Company Website', 'Company Website'), ('Job Board', 'Job Board'), ('Other', 'Other')], max_length=50)),
                ('tags', models.TextField(blank=True, help_text='Comma-separated tags')),
                ('resume_file', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('resume_text', models.TextField(blank=True)),
                ('interviewers', models.TextField(blank=True)),
                ('interview_dates', models.TextField(blank=True)),
                ('comments_ta', models.TextField(blank=True, verbose_name='Technical Assessment Comments')),
                ('comments_initial_call', models.TextField(blank=True, verbose_name='Initial Call Comments')),
                ('comments_evaluation', models.TextField(blank=True, verbose_name='Evaluation Comments')),
                ('overall_feedback', models.TextField(blank=True)),
                ('final_decision', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_status_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
