# Generated by Django 5.2.2 on 2025-08-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0002_jobposition_applicant_job_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobposition",
            name="tags",
            field=models.TextField(blank=True, help_text="Comma-separated tags"),
        ),
    ]
