# Generated by Django 5.2.2 on 2024-07-08 12:00

from pgvector.django import VectorExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ats', '0003_jobposition_tags'),
    ]

    operations = [
        VectorExtension(),
    ]
