# Generated by Django 5.2.2 on 2025-08-25 15:52

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ats", "0004_add_vector_extension"),
    ]

    operations = [
        migrations.AddField(
            model_name="applicant",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
        migrations.AddField(
            model_name="jobposition",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=384, null=True),
        ),
    ]
